defaults:
  branches:
  - release-1.26
  repo-allowlist:
  - api
org: istio
repo: api
transforms:
- env:
    GCS_BUCKET: istio-build-private/dev
  job-allowlist:
  - build_release-1.26
  - gencheck_release-1.26
  job-type:
  - presubmit
- job-allowlist:
  - build_release-1.26
  - gencheck_release-1.26
  job-type:
  - postsubmit
  labels:
    preset-override-envoy: "true"
